### ISSUE TITLE
Required templates not in repo

### ISSUE THREAD

**Issue by insacuri** [companieshouse/MojoX-Plugin-PODRenderer#1]
At the moment the templates that work with this (so that you can /perldoc and get a nice homepage aren't with this repo which means that every repo that wants that functionality is required to have a copy of those templates (shouldn't have to say why that is bad ;) ).  Need to find a way to put them in this repo and have mojolicious be able to find them.

**Comment by ian-kent** [comment]
Being looked at as part of admin bar plugin, potential solution is to inline the templates into the DATA section of a module so they're bundled with the plugin (it's how Mojolicious does it with its own templates)
